Name:           ros-melodic-dynamic-reconfigure
Version:        1.5.49
Release:        1%{?dist}
Summary:        ROS dynamic_reconfigure package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/dynamic_reconfigure
Source0:        %{name}-%{version}.tar.gz

Requires:       boost-devel
Requires:       ros-melodic-message-runtime
Requires:       ros-melodic-roscpp
Requires:       ros-melodic-roslib
Requires:       ros-melodic-rospy
Requires:       ros-melodic-rosservice
Requires:       ros-melodic-std-msgs
BuildRequires:  boost-devel
BuildRequires:  ros-melodic-catkin >= 0.5.87
BuildRequires:  ros-melodic-message-generation
BuildRequires:  ros-melodic-roscpp
BuildRequires:  ros-melodic-roscpp-serialization
BuildRequires:  ros-melodic-rostest
BuildRequires:  ros-melodic-std-msgs

%description
This unary stack contains the dynamic_reconfigure package which provides a means
to change node parameters at any time without having to restart the node.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Fri Mar 02 2018 Mikael Arguedas <mikael@osrfoundation.org> - 1.5.49-1
- Autogenerated by Bloom

* Fri Mar 02 2018 Mikael Arguedas <mikael@osrfoundation.org> - 1.5.49-0
- Autogenerated by Bloom

