Name:           ros-lunar-dynamic-reconfigure
Version:        1.5.49
Release:        0%{?dist}
Summary:        ROS dynamic_reconfigure package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/dynamic_reconfigure
Source0:        %{name}-%{version}.tar.gz

Requires:       boost-devel
Requires:       ros-lunar-message-runtime
Requires:       ros-lunar-roscpp
Requires:       ros-lunar-roslib
Requires:       ros-lunar-rospy
Requires:       ros-lunar-rosservice
Requires:       ros-lunar-std-msgs
BuildRequires:  boost-devel
BuildRequires:  ros-lunar-catkin >= 0.5.87
BuildRequires:  ros-lunar-message-generation
BuildRequires:  ros-lunar-roscpp
BuildRequires:  ros-lunar-roscpp-serialization
BuildRequires:  ros-lunar-rostest
BuildRequires:  ros-lunar-std-msgs

%description
This unary stack contains the dynamic_reconfigure package which provides a means
to change node parameters at any time without having to restart the node.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/lunar/setup.sh" ]; then . "/opt/ros/lunar/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/lunar" \
        -DCMAKE_PREFIX_PATH="/opt/ros/lunar" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/lunar/setup.sh" ]; then . "/opt/ros/lunar/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/lunar

%changelog
* Thu Jul 27 2017 Mikael Arguedas <mikael@osrfoundation.org> - 1.5.49-0
- Autogenerated by Bloom

* Fri Apr 07 2017 Mikael Arguedas <mikael@osrfoundation.org> - 1.5.48-0
- Autogenerated by Bloom

* Fri Apr 07 2017 Mikael Arguedas <mikael@osrfoundation.org> - 1.5.47-1
- Autogenerated by Bloom

* Mon Mar 27 2017 Mikael Arguedas <mikael@osrfoundation.org> - 1.5.47-0
- Autogenerated by Bloom

* Wed Feb 22 2017 Mikael Arguedas <mikael@osrfoundation.org> - 1.5.46-0
- Autogenerated by Bloom

